import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  ticonmenup: {
    width: 30,
    height: 30,
  },
  mgbtmp: {
    marginTop: 25,
    marginLeft: 15,
    width: 40,
  },
  btnubno: {
    position: 'absolute',

    right: 20,
    top: 20,
    display: 'flex',
    flexDirection: 'row',
  },
  mgbtmp1: {
    marginTop: -28,
    marginLeft: 315,
    backgroundColor: '#E8F7FC',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  mgbtmp2: {
    backgroundColor: '#B9E9F9',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  contNoti: {
    marginTop: 20,
    width: '100%',
    height: 48,

    marginBottom: 8,
    display: 'flex',
    flexDirection: 'row-reverse',
    position: 'relative',
  },
  mgbtmp3: {
    position: 'absolute',
    width: '13%',
    height: 48,
    backgroundColor: '#E8F7FC',
    left: '6%',
    borderRadius: 10,
  },
  ticonnot: {
    width: 36,
    height: 36,
    alignSelf: 'center',
    marginTop: 4,
  },
  tamiconbus: {
    width: 25,
    height: 25,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  borde: {
    flex: 1,
  },
  passwordContainer: {
    flexDirection: 'row',
    borderRadius: 10,
    marginLeft: 15,
    backgroundColor: '#E8F7FC',
    height: 48,
    width: 280,
    marginTop: -55,
  },
  passwordContainer1: {
    flexDirection: 'row',
    marginLeft: 25,
    height: 48,
    width: 280,
    marginTop: 25,
  },
  txtpromo: {
    fontSize: 30,
    fontWeight: '700',
    color: '#ACB5C6',
  },
  box4: {
    width: '95%',
    margin: 5,
    marginTop: 0,
    height: 233,
    backgroundColor: '#FFF',
    borderColor: '#F1F1F1',
    borderRadius: 10,
    position: 'relative',
    shadowOffset: {width: 10, height: 10},
    shadowColor: 'black',
    shadowOpacity: 10.0,
    elevation: 4,
  },
  boxpromo: {
    width: 340,
    margin: 5,
    marginTop: 10,
    height: 160,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#ECECF5',
    borderRadius: 10,
    elevation: 2,
  },
  image: {
    width: 340,
    height: 160,
    borderRadius: 10,
  },
  txtprbox: {
    fontSize: 28,
    color: '#FFF',
    marginTop: -145,
    marginLeft: 25,
    fontWeight: 'bold',
    width: 182,
  },
  txtprboxsb: {
    fontSize: 12,
    color: '#FFFFFF',
    marginLeft: 25,
    fontWeight: '700',
    width: 182,
  },
  opatext: {
    opacity: 0.8,
    width: 242,
    backgroundColor: '#706A6A',
    borderRadius: 10,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
  },
  box3: {
    marginTop: -12,
    width: 160,
    margin: 12,
    height: 160,
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: '#ECECF5',
    borderRadius: 10,
  },
  // box5: {
  //   width: 80,
  //   margin: 4,
  //   height: 80,
  //   backgroundColor: '#FFFFFF',
  //   elevation: 2.5,
  //   shadowOpacity: 87.8,
  //   borderColor: '#ECECF5',
  //   borderRadius: 15,
  //   marginTop: 2,
  //   marginBottom: 10,
  // },
  box5: {
    maxWidth: 80,
    margin: 4,
    maxHeight: 80,
    backgroundColor: '#FFFFFF',
    elevation: 2.5,
    shadowOpacity: 87.8,
    borderColor: '#ECECF5',
    borderRadius: 15,
    marginTop: 2,
    marginBottom: 10,
  },
  boxactive: {
    width: 80,
    margin: 4,
    height: 80,
    backgroundColor: '#1DAFF1',
    elevation: 2.5,
    shadowOpacity: 87.8,
    borderColor: '#ECECF5',
    borderRadius: 15,
    marginTop: 2,
    marginBottom: 10,
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    position: 'relative',
  },
  // row: {
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   marginTop: 5,
  //   marginBottom: 10,
  // },
  row: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    marginBottom: 10,
    width: '100%',
  },
  rowItems: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 5,
    marginBottom: 10,
    width: '50%',
  },
  row2: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
    borderRadius: 2,
  },
  rowbtncarrito: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemCarrito: {
    width: '90%',
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    height: 60,
    borderRadius: 2,
    elevation: 1,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    position: 'relative',
    marginBottom: 5,
    borderBottomRightRadius: 15,
    borderTopRightRadius: 15,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 9,
  },
  rowbtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    bottom: 0,
    right: 0,
    position: 'absolute',
    direction: 'ltr',
  },
  ticonnot1: {
    width: 70,
    height: 70,
    marginLeft: 5,
    marginTop: 5,
  },
  ticonnot12: {
    width: 35,
    height: 35,
  },
  ticonnot2: {
    width: '80%',
    height: 100,
    marginLeft: 15,
    marginTop: 24,
    borderRadius: 10,
  },
  ticonnot3: {
    width: 23,
    height: 23,
    position: 'absolute',
    right: 5,
    borderRadius: 10,
    top: 5,
  },
  txttppro: {
    textAlign: 'center',
    top: 15,
    fontSize: 12,
    fontWeight: '600',
    color: '#3CBAF3',
  },
  txtprofile: {
    position: 'absolute',
    textAlign: 'left',
    fontSize: 26,
    fontWeight: '600',
    color: '#AAB5C7',
    marginLeft: 40,
    marginTop: 1,
  },
  imgprofile: {
    alignSelf: 'center',
    width: 150,
    height: 150,
  },
  fotoeditar: {
    marginLeft: 115,
    width: 50,
    height: 50,
    marginTop: -27,
  },
  txtnombreprofile: {
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '500',
    color: '#66656B',
    marginBottom: 1,
  },
  txtdireccion: {
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 40,
  },
  viewprofilepedidos: {
    marginTop: 10,
    flex: 0.3,
    backgroundColor: 'white',
    borderWidth: 1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    width: 300,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 50,
  },
  box: {
    width: 150,
    height: 98,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
    borderColor: '#EDF0F4',
  },
  box7: {
    width: 150,
    height: 98,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    borderColor: '#EDF0F4',
  },
  container1: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
  },
  fotopedidosperfil: {
    marginLeft: 7,
    marginTop: 15,
    width: 40,
    height: 40,
  },
  fotofavperfil: {
    marginLeft: 2,
    marginTop: 15,
    width: 40,
    height: 40,
  },
  textpedidosperfil: {
    textAlign: 'center',
    fontWeight: '600',
    marginTop: -37,
    marginLeft: 10,
  },
  box10: {
    borderBottomWidth: 1,
    width: 320,
    alignSelf: 'center',
    borderColor: '#EDF0F4',
    padding: 4,
    flexDirection: 'row',
    backgroundColor: 'transparent',
    height: 48,
  },

  iconoperfil: {
    height: 27,
    width: 27,
    marginBottom: 2,
    marginTop: 2,
  },
  numeroperfil: {
    color: '#1580F7',
    fontWeight: '800',
    fontSize: 24,
    marginLeft: 50,
  },
  box6: {
    backgroundColor: '#FFFFFF',
  },

  box13: {
    borderColor: '#EEEEEE',
    borderWidth: 1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    width: 350,
    alignSelf: 'center',
  },

  box11: {
    borderColor: '#EEEEEE',
    borderWidth: 1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    width: 350,
    alignSelf: 'center',
    marginTop: 10,
  },

  mgbtmp5: {
    marginTop: 1,
    marginLeft: 15,
    width: 30,
  },

  botoneditar: {
    width: 60,
    height: 30,
    marginLeft: 230,
    marginTop: -30,
  },
  botonnoti: {
    width: 30,
    height: 30,
    marginLeft: 280,
    marginTop: 30,
  },

  textoeditperfil: {},
  wea: {
    marginLeft: 100,
  },
  btnSeguir: {
    marginTop: 10,
    backgroundColor: '#1580F7',
    height: 45,
    width: 300,
    alignSelf: 'center',
    borderBottomEndRadius: 10,
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },

  textbutton: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    alignSelf: 'center',
    marginTop: 8,
  },
  NProtxt: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 20,
    marginVertical: 3,
  },
  SNPtxt: {
    fontSize: 14,
    marginLeft: 20,
    color: '#B7B7B7',
  },
  Pretxt: {
    marginLeft: 20,
    color: '#2EE107',
    fontSize: 18,
  },
  txtbtn: {
    fontSize: 20,
    color: '#FFF',
    textAlign: 'center',
    zIndex: 3,
    top: 5,
  },
  txtbtn2: {
    fontSize: 20,
    height: 40,
    top: 5,
    color: '#FFF',
    fontWeight: 'bold',
    textAlign: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    display: 'flex',
  },
  txtbtn1: {
    fontSize: 15,
    color: '#FFF',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  txtbtn12: {
    fontSize: 15,
    color: '#FFF',
    textAlign: 'center',
    fontWeight: 'bold',
    marginTop: 8,
  },
  btnmas: {
    backgroundColor: '#FD178F',
    width: 40,
    height: 40,
    borderBottomRightRadius: 10,
    borderTopLeftRadius: 10,
    zIndex: 1,
  },

  btnmas1: {
    backgroundColor: '#1DAFF1',
    width: 40,
    marginRight: 0,
    borderTopLeftRadius: 10,
    bottom: 0,
    left: 8,
    padding: 0,
  },
  btnmas12: {
    backgroundColor: '#4CB96A',
    width: 150,
    height: 35,
    borderTopLeftRadius: 10,
    borderBottomRightRadius: 10,
    marginTop: 9.9,
    marginLeft: 191,
    paddingHorizontal: 15,
  },
  btncarrito: {
    marginLeft: 80,
    backgroundColor: '#1680F8',
    height: '97%',
    width: 105,
    alignItems: 'center',
    textAlign: 'center',
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    position: 'absolute',
    right: 0,
    top: 2,
  },

  txtCarritobtn: {
    color: '#FFF',
    textAlign: 'center',
    marginTop: 15,
    marginLeft: -45,
  },
  txttotalbtncarrito: {
    fontSize: 18,
    marginLeft: 25,
    fontWeight: '600',
  },
  achique: {
    width: 50,
    marginTop: -45,
    marginLeft: 120,
    marginBottom: -20,
  },
  row1: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    marginBottom: 10,
  },
  iconosarriba: {
    width: '80%',
    height: 20,
    marginTop: 5,
    alignSelf: 'center',
  },
  contIcons: {
    position: 'absolute',
    display: 'flex',
    flexDirection: 'row',
    right: 5,
    top: 25,
  },
  mgbtmp10: {
    marginRight: 5,
    backgroundColor: '#B9E9F9',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  listview: {
    flex: 1,
    marginHorizontal: 18,
    display: 'flex',
  },
  listnone: {
    display: 'none',
  },
  txtbtncarro: {
    color: '#FFFFFF',
    fontSize: 20,
  },
});
export default styles;
